from temporal_normalization.rules.timespan_regex import (
    AGES_ARABIC_NOTATION,
    AGES_NOTATIONS,
    AGES_ROMAN_NOTATION,
    ARTICLE_AL,
    CASE_INSENSITIVE,
    CENTURY_LABEL,
    FIRST_HALF,
    FIRST_QUARTER,
    FORTH_QUARTER,
    MIDDLE_OF,
    MILLENNIUM_LABEL,
    REGEX_OR,
    REGEX_INTERVAL_CONJUNCTION,
    REGEX_INTERVAL_DELIMITER,
    REGEX_INTERVAL_PREFIX,
    REGEX_PUNCTUATION_UNLIMITED,
    SECOND_HALF,
    SECOND_QUARTER,
    THIRD_QUARTER,
)

"""
Regular expressions for those time intervals that are stored
as ages (centuries and millenniums)
"""

# -------------------------
# CENTURY TIME PERIOD (ROMAN NOTATION)
# -------------------------

CENTURY_ROMAN = CENTURY_LABEL + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION

CENTURY_ROMAN_FIRST_HALF = FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN
CENTURY_ROMAN_SECOND_HALF = SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN
CENTURY_ROMAN_MIDDLE_OF = MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN
CENTURY_ROMAN_FIRST_QUARTER = FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN
CENTURY_ROMAN_SECOND_QUARTER = SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN
CENTURY_ROMAN_THIRD_QUARTER = THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN
CENTURY_ROMAN_FORTH_QUARTER = FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN

CENTURY_ROMAN_OPTIONS = (
        "("
        + "(" + CENTURY_ROMAN_FIRST_HALF + ")" + REGEX_OR
        + "(" + CENTURY_ROMAN_SECOND_HALF + ")" + REGEX_OR
        + "(" + CENTURY_ROMAN_MIDDLE_OF + ")" + REGEX_OR
        + "(" + CENTURY_ROMAN_FIRST_QUARTER + ")" + REGEX_OR
        + "(" + CENTURY_ROMAN_SECOND_QUARTER + ")" + REGEX_OR
        + "(" + CENTURY_ROMAN_THIRD_QUARTER + ")" + REGEX_OR
        + "(" + CENTURY_ROMAN_FORTH_QUARTER + ")" + REGEX_OR
        + "(" + CENTURY_ROMAN + ")"
        + ")"
)


# -------------------------
# CENTURY TIME PERIOD (ARABIC NOTATION)
# -------------------------

CENTURY_ARABIC = CENTURY_LABEL + REGEX_PUNCTUATION_UNLIMITED + AGES_ARABIC_NOTATION

CENTURY_ARABIC_FIRST_HALF = FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC
CENTURY_ARABIC_SECOND_HALF = SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC
CENTURY_ARABIC_MIDDLE_OF = MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC
CENTURY_ARABIC_FIRST_QUARTER = FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC
CENTURY_ARABIC_SECOND_QUARTER = SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC
CENTURY_ARABIC_THIRD_QUARTER = THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC
CENTURY_ARABIC_FORTH_QUARTER = FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC

CENTURY_ARABIC_OPTIONS = (
        "("
        + "(" + CENTURY_ARABIC_FIRST_HALF + ")" + REGEX_OR
        + "(" + CENTURY_ARABIC_SECOND_HALF + ")" + REGEX_OR
        + "(" + CENTURY_ARABIC_MIDDLE_OF + ")" + REGEX_OR
        + "(" + CENTURY_ARABIC_FIRST_QUARTER + ")" + REGEX_OR
        + "(" + CENTURY_ARABIC_SECOND_QUARTER + ")" + REGEX_OR
        + "(" + CENTURY_ARABIC_THIRD_QUARTER + ")" + REGEX_OR
        + "(" + CENTURY_ARABIC_FORTH_QUARTER + ")" + REGEX_OR
        + "(" + CENTURY_ARABIC + ")"
        + ")"
)


# -------------------------
# MILLENNIUM TIME PERIOD (ROMAN NOTATION)
# -------------------------

MILLENNIUM_ROMAN = MILLENNIUM_LABEL + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION

MILLENNIUM_ROMAN_FIRST_HALF = FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN
MILLENNIUM_ROMAN_SECOND_HALF = SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN
MILLENNIUM_ROMAN_MIDDLE_OF = MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN
MILLENNIUM_ROMAN_FIRST_QUARTER = FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN
MILLENNIUM_ROMAN_SECOND_QUARTER = SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN
MILLENNIUM_ROMAN_THIRD_QUARTER = THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN
MILLENNIUM_ROMAN_FORTH_QUARTER = FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN

MILLENNIUM_ROMAN_OPTIONS = (
        "("
        + "(" + MILLENNIUM_ROMAN_FIRST_HALF + ")" + REGEX_OR
        + "(" + MILLENNIUM_ROMAN_SECOND_HALF + ")" + REGEX_OR
        + "(" + MILLENNIUM_ROMAN_MIDDLE_OF + ")" + REGEX_OR
        + "(" + MILLENNIUM_ROMAN_FIRST_QUARTER + ")" + REGEX_OR
        + "(" + MILLENNIUM_ROMAN_SECOND_QUARTER + ")" + REGEX_OR
        + "(" + MILLENNIUM_ROMAN_THIRD_QUARTER + ")" + REGEX_OR
        + "(" + MILLENNIUM_ROMAN_FORTH_QUARTER + ")" + REGEX_OR
        + "(" + MILLENNIUM_ROMAN + ")"
        + ")"
)


# -------------------------
# MILLENNIUM TIME PERIOD (ARABIC NOTATION)
# -------------------------

MILLENNIUM_ARABIC = MILLENNIUM_LABEL + REGEX_PUNCTUATION_UNLIMITED + AGES_ARABIC_NOTATION

MILLENNIUM_ARABIC_FIRST_HALF = FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC
MILLENNIUM_ARABIC_SECOND_HALF = SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC
MILLENNIUM_ARABIC_MIDDLE_OF = MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC
MILLENNIUM_ARABIC_FIRST_QUARTER = FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC
MILLENNIUM_ARABIC_SECOND_QUARTER = SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC
MILLENNIUM_ARABIC_THIRD_QUARTER = THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC
MILLENNIUM_ARABIC_FORTH_QUARTER = FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC

MILLENNIUM_ARABIC_OPTIONS = (
        "("
        + "(" + MILLENNIUM_ARABIC_FIRST_HALF + ")" + REGEX_OR
        + "(" + MILLENNIUM_ARABIC_SECOND_HALF + ")" + REGEX_OR
        + "(" + MILLENNIUM_ARABIC_MIDDLE_OF + ")" + REGEX_OR
        + "(" + MILLENNIUM_ARABIC_FIRST_QUARTER + ")" + REGEX_OR
        + "(" + MILLENNIUM_ARABIC_SECOND_QUARTER + ")" + REGEX_OR
        + "(" + MILLENNIUM_ARABIC_THIRD_QUARTER + ")" + REGEX_OR
        + "(" + MILLENNIUM_ARABIC_FORTH_QUARTER + ")" + REGEX_OR
        + "(" + MILLENNIUM_ARABIC + ")"
        + ")"
)


# -------------------------
# OTHER CENTURY TIME PERIOD (ROMAN NOTATION)
# -------------------------

OTHER_CENTURY_ROMAN_FIRST_HALF = FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION
OTHER_CENTURY_ROMAN_SECOND_HALF = SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION
OTHER_CENTURY_ROMAN_MIDDLE_OF = MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION
OTHER_CENTURY_ROMAN_FIRST_QUARTER = FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION
OTHER_CENTURY_ROMAN_SECOND_QUARTER = SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION
OTHER_CENTURY_ROMAN_THIRD_QUARTER = THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION
OTHER_CENTURY_ROMAN_FORTH_QUARTER = FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION

OTHER_CENTURY_ROMAN_OPTIONS = (
        "("
        + "(" + OTHER_CENTURY_ROMAN_FIRST_HALF + ")"
        + REGEX_OR + "(" + OTHER_CENTURY_ROMAN_SECOND_HALF + ")"
        + REGEX_OR + "(" + OTHER_CENTURY_ROMAN_MIDDLE_OF + ")"
        + REGEX_OR + "(" + OTHER_CENTURY_ROMAN_FIRST_QUARTER + ")"
        + REGEX_OR + "(" + OTHER_CENTURY_ROMAN_SECOND_QUARTER + ")"
        + REGEX_OR + "(" + OTHER_CENTURY_ROMAN_THIRD_QUARTER + ")"
        + REGEX_OR + "(" + OTHER_CENTURY_ROMAN_FORTH_QUARTER + ")"
        + ")"
)

OTHER_CENTURY_ROMAN_INTERVAL = (
        CASE_INSENSITIVE
        + "("
        + OTHER_CENTURY_ROMAN_OPTIONS
        + REGEX_INTERVAL_DELIMITER
        + "(" + OTHER_CENTURY_ROMAN_OPTIONS + REGEX_OR + AGES_ROMAN_NOTATION + ")"
        + ")"
)


# -------------------------
# GLOBAL OPTIONS
# -------------------------

CENTURY_OPTIONS = CASE_INSENSITIVE + "(" + CENTURY_ARABIC_OPTIONS + REGEX_OR + CENTURY_ROMAN_OPTIONS + ")"

MILLENNIUM_OPTIONS = CASE_INSENSITIVE + "(" + MILLENNIUM_ARABIC_OPTIONS + REGEX_OR + MILLENNIUM_ROMAN_OPTIONS + ")"

CENTURY_INTERVAL_BASE = (
        CASE_INSENSITIVE
        + CENTURY_OPTIONS
        + REGEX_INTERVAL_DELIMITER
        + "(" + CENTURY_OPTIONS + REGEX_OR + AGES_NOTATIONS + ")"
)

CENTURY_INTERVAL_PREFIXED = (
        CASE_INSENSITIVE
        + REGEX_INTERVAL_PREFIX
        + CENTURY_OPTIONS
        + REGEX_INTERVAL_CONJUNCTION
        + "(" + "(" + ARTICLE_AL + AGES_NOTATIONS + ")" + REGEX_OR + CENTURY_OPTIONS + ")"
)

MILLENNIUM_INTERVAL_BASE = (
        CASE_INSENSITIVE
        + MILLENNIUM_OPTIONS
        + REGEX_INTERVAL_DELIMITER
        + "(" + MILLENNIUM_OPTIONS + REGEX_OR + AGES_NOTATIONS + ")"
)

MILLENNIUM_INTERVAL_PREFIXED = (
        CASE_INSENSITIVE
        + REGEX_INTERVAL_PREFIX
        + MILLENNIUM_OPTIONS
        + REGEX_INTERVAL_CONJUNCTION
        + "(" + "(" + ARTICLE_AL + AGES_NOTATIONS + ")" + REGEX_OR + MILLENNIUM_OPTIONS + ")"
)


CENTURY_REGEXES = {
    CENTURY_INTERVAL_BASE,
    CENTURY_INTERVAL_PREFIXED,
    CENTURY_OPTIONS,
    OTHER_CENTURY_ROMAN_INTERVAL,
    OTHER_CENTURY_ROMAN_OPTIONS,
}

MILLENNIUM_REGEXES = {
    MILLENNIUM_INTERVAL_BASE,
    MILLENNIUM_INTERVAL_PREFIXED,
    MILLENNIUM_OPTIONS,
}
