from temporal_normalization.rules.timespan_regex import (
    AGES_ARABIC_NOTATION,
    AGES_NOTATIONS,
    AGES_ROMAN_NOTATION,
    ARTICLE_AL,
    CENTURY_LABEL,
    FIRST_HALF,
    FIRST_QUARTER,
    FORTH_QUARTER,
    MIDDLE_OF,
    MILLENNIUM_LABEL,
    REGEX_INTERVAL_CONJUNCTION,
    REGEX_INTERVAL_DELIMITER,
    REGEX_INTERVAL_PREFIX,
    REGEX_PUNCTUATION_UNLIMITED,
    SECOND_HALF,
    SECOND_QUARTER,
    THIRD_QUARTER,
)

"""
Regular expressions for those time intervals that are stored
as ages (centuries and millenniums)
"""

CENTURY_ROMAN_LABEL = CENTURY_LABEL + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION
CENTURY_ROMAN_ITEMS = [
    FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN_LABEL,
    SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN_LABEL,
    MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN_LABEL,
    FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN_LABEL,
    SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN_LABEL,
    THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN_LABEL,
    FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ROMAN_LABEL,
    CENTURY_ROMAN_LABEL,
]
CENTURY_ROMAN_OPTIONS = "|".join(f"({pattern})" for pattern in CENTURY_ROMAN_ITEMS)


CENTURY_ARABIC_LABEL = CENTURY_LABEL + REGEX_PUNCTUATION_UNLIMITED + AGES_ARABIC_NOTATION
CENTURY_ARABIC_ITEMS = [
    FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC_LABEL,
    SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC_LABEL,
    MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC_LABEL,
    FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC_LABEL,
    SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC_LABEL,
    THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC_LABEL,
    FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + CENTURY_ARABIC_LABEL,
    CENTURY_ARABIC_LABEL,
]
CENTURY_ARABIC_OPTIONS = "|".join(f"({pattern})" for pattern in CENTURY_ARABIC_ITEMS)


MILLENNIUM_ROMAN_LABEL = MILLENNIUM_LABEL + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION
MILLENNIUM_ROMAN_ITEMS = [
    FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN_LABEL,
    SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN_LABEL,
    MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN_LABEL,
    FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN_LABEL,
    SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN_LABEL,
    THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN_LABEL,
    FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ROMAN_LABEL,
    MILLENNIUM_ROMAN_LABEL,
]
MILLENNIUM_ROMAN_OPTIONS = "|".join(f"({pattern})" for pattern in MILLENNIUM_ROMAN_ITEMS)


MILLENNIUM_ARABIC_LABEL = MILLENNIUM_LABEL + REGEX_PUNCTUATION_UNLIMITED + AGES_ARABIC_NOTATION
MILLENNIUM_ARABIC_ITEMS = [
    FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC_LABEL,
    SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC_LABEL,
    MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC_LABEL,
    FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC_LABEL,
    SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC_LABEL,
    THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC_LABEL,
    FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + MILLENNIUM_ARABIC_LABEL,
    MILLENNIUM_ARABIC_LABEL,
]
MILLENNIUM_ARABIC_OPTIONS = "|".join(f"({pattern})" for pattern in MILLENNIUM_ARABIC_ITEMS)


OTHER_CENTURY_ROMAN_ITEMS = [
    FIRST_HALF + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION,
    SECOND_HALF + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION,
    MIDDLE_OF + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION,
    FIRST_QUARTER + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION,
    SECOND_QUARTER + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION,
    THIRD_QUARTER + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION,
    FORTH_QUARTER + REGEX_PUNCTUATION_UNLIMITED + AGES_ROMAN_NOTATION,
]
OTHER_CENTURY_ROMAN_OPTIONS = "|".join(f"({pattern})" for pattern in OTHER_CENTURY_ROMAN_ITEMS)


# -------------------------
# GLOBAL OPTIONS
# -------------------------

CENTURY_OPTIONS = "(" + CENTURY_ARABIC_OPTIONS + "|" + CENTURY_ROMAN_OPTIONS + ")"

MILLENNIUM_OPTIONS = "(" + MILLENNIUM_ARABIC_OPTIONS + "|" + MILLENNIUM_ROMAN_OPTIONS + ")"

CENTURY_INTERVAL_BASE = (
        CENTURY_OPTIONS
        + REGEX_INTERVAL_DELIMITER
        + "(" + CENTURY_OPTIONS + "|" + AGES_NOTATIONS + ")"
)

CENTURY_INTERVAL_PREFIXED = (
        REGEX_INTERVAL_PREFIX
        + CENTURY_OPTIONS
        + REGEX_INTERVAL_CONJUNCTION
        + "(" + "(" + ARTICLE_AL + AGES_NOTATIONS + ")" + "|" + CENTURY_OPTIONS + ")"
)

MILLENNIUM_INTERVAL_BASE = (
        MILLENNIUM_OPTIONS
        + REGEX_INTERVAL_DELIMITER
        + "(" + MILLENNIUM_OPTIONS + "|" + AGES_NOTATIONS + ")"
)

MILLENNIUM_INTERVAL_PREFIXED = (
        REGEX_INTERVAL_PREFIX
        + MILLENNIUM_OPTIONS
        + REGEX_INTERVAL_CONJUNCTION
        + "(" + "(" + ARTICLE_AL + AGES_NOTATIONS + ")" + "|" + MILLENNIUM_OPTIONS + ")"
)

OTHER_CENTURY_ROMAN_INTERVAL = (
        OTHER_CENTURY_ROMAN_OPTIONS
        + REGEX_INTERVAL_DELIMITER
        + "(" + OTHER_CENTURY_ROMAN_OPTIONS + "|" + AGES_ROMAN_NOTATION + ")"
)


CENTURY_REGEXES = [
    CENTURY_INTERVAL_BASE,
    CENTURY_INTERVAL_PREFIXED,
    CENTURY_OPTIONS,
    OTHER_CENTURY_ROMAN_INTERVAL,
    OTHER_CENTURY_ROMAN_OPTIONS,
]

MILLENNIUM_REGEXES = [
    MILLENNIUM_INTERVAL_BASE,
    MILLENNIUM_INTERVAL_PREFIXED,
    MILLENNIUM_OPTIONS,
]
