"""
Regular expressions for those time intervals that are stored
as an unknown time period
"""

UNKNOWN_ITEMS = [
    r"4/4 sec\.",
    r"17 nov\. 375\-9 aug\. 378 a\.chr\.",
    r"1884 martie 28/aprilie 09",
    r"189-45",
    r"al doile afert al s1900",
    r"an[ ]?\d{1,2}[\?]?",
    r"cultura inca sau chachapoya\?",
    r"datat",
    r"dinastia xxv",
    r"dinastia xxvi \(dinastia saita\)",
    r"dinastia xxvi \(perioada saita\)",
    r"dinastia xxvii \(prima stapanire persana\)",
    r"nesemnat",
    r"disparuta din uz si din zona; existenta in muzee",
    r"epoca severica tarzie",
    r"grupa a iv-a",
    r"grupa a v-a",
    r"grupa iii",
    r"grupa iv",
    r"grupa v",
    r"la tene",
    r"lama de secol xvi/xvii, garda si manerul ulterioare",
    r"leat 7208 \(1699-1700\)",
    r"mai, dni 15, leat 7232",
    r"mesiata.*",
    r"fev\. dni 2 leat 7157",
    r"iulie 28",
    r"iunie 01",
    r"iunie 20, leat 7173 \(1665\)",
    r"iunie, dni 2, leat 7235",
    r"august 04",
    r"oct\. 10 dni, leat 1730",
    r"octombrie 23, 1777",
    r"noiembrie 22",
    r"noiembrie 24",
    r"perioada lui carol x al frantei",
    r"perioada domniei regelui carol al ii-lea",
    r"perioada regelui carol al ii-lea",
    r"regatul nou\?",
    r"21/2, sc\.i, a\.c\.",
    r"21/2; sc i a\.c\.",
    r"286/5-282/1",
    r"286/5-282/1 a\. chr",
    r"15\(\…\)4",
    r"154\(\…\)",
    r"158\(\…\)",
    r"162\(\?\)",
    r"16\[\ ]",
]
UNKNOWN_OPTIONS = "|".join(UNKNOWN_ITEMS)
UNKNOWN_REGEXES = "^(-" + UNKNOWN_OPTIONS + ")$"
